### ISSUE TITLE
9th November, 2021 Peer To Peer Code Review Exercise

### ISSUE THREAD

**Issue by JEFFKAY16** [gracekabaghe/to-do#6]
## Peer To Peer Code Review Exercise

Hi Grace, awesome codebase with clean Js practices. Below are suggested ways of how we can improve the codebase:

- It would be nice to have the line spaces [found here](https://github.com/gracekabaghe/to-do/blob/b7b75fb1d95b130942d430a7d0ab814b559033fe/src/index.html#L26-L27)removed.
- It would be nice to have some universal styling using the `*` and removing default stylings such as padding and margins. You may also consider using the `box-sizing: border-box` property to account for any border and padding in the values you specify for an element's width and height.

**Comment by gracekabaghe** [comment]
Thanks:
- removed whitespace in index.html
- added box-sizing
